import { useState } from 'react';
import { ArrowLeft, ArrowRight, Save } from 'lucide-react';
import localProductsApi from '../../../../config/sub_api/product_management_api/local_products_api';
import { getApiError } from '../../../../config/api';
import erpApi from '../../../../config/sub_api/erp_api/erpApi';

const steps = ['Basic', 'Category', 'Supplier', 'Inventory', 'Images', 'Variants', 'Attributes', 'Review'];

export default function ProductAddWizardPage(){
 const [step,setStep]=useState(0); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
 const [form,setForm]=useState({ product_name:'', sku:'', product_type:'single', category_id:'', sub_category_id:'', model:'', type:'', supplier_id:'', supplier_sku:'', cost_price:'', opening_stock:'', low_stock_alert_qty:5, image_url:'', variants_json:'[]', attributes_json:'{}' });
 function set(k,v){setForm(f=>({...f,[k]:v}));} function next(){setStep(s=>Math.min(s+1,steps.length-1));} function back(){setStep(s=>Math.max(s-1,0));}
 async function save(e){e?.preventDefault(); try{setSaving(true);setError('');setMessage(''); const payload={ product_name:form.product_name, name:form.product_name, sku:form.sku, product_sku:form.sku, product_type:form.product_type, category_id:form.category_id, sub_category_id:form.sub_category_id, model:form.model, type:form.type, image_url:form.image_url, attributes: JSON.parse(form.attributes_json || '{}')}; const r=await localProductsApi.createProduct(payload); if(form.supplier_id && form.sku){await erpApi.addSupplierProduct({ supplier_id:form.supplier_id, local_sku:form.sku, supplier_sku:form.supplier_sku, product_name:form.product_name, cost_price:form.cost_price, lead_time_days:7 });} setMessage(`Product saved successfully. ID: ${r?.data?.data?.id || r?.data?.product?.id || '-'}`);}catch(err){setError(getApiError(err,'Product save failed. Check required fields.'));}finally{setSaving(false);} }
 return <form onSubmit={save} className="page-shell"><div className="page-header-card"><h1 className="text-xl font-bold">Add Product</h1><p className="mt-1 text-sm text-slate-500">Clean step form with supplier, inventory, image, variant and attribute sections.</p></div><div className="erp-card flex flex-wrap gap-2">{steps.map((x,i)=><button type="button" key={x} onClick={()=>setStep(i)} className={`rounded-full border px-3 py-1 text-xs font-bold ${i===step?'border-yellow-300 bg-yellow-300 text-slate-950':'border-white/10 bg-[#070B14] text-slate-400'}`}>{i+1}. {x}</button>)}</div>{error&&<div className="rounded-xl border border-red-400/20 bg-red-500/10 px-3 py-2 text-xs text-red-200">{error}</div>}{message&&<div className="rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-xs text-emerald-200">{message}</div>}
 <div className="erp-card min-h-[340px]">
 {step===0&&<div className="grid gap-3 md:grid-cols-2"><input className="erp-input" required placeholder="Product name" value={form.product_name} onChange={e=>set('product_name',e.target.value)}/><input className="erp-input" required placeholder="SKU" value={form.sku} onChange={e=>set('sku',e.target.value)}/><select className="erp-input" value={form.product_type} onChange={e=>set('product_type',e.target.value)}><option value="single">Single product</option><option value="parent">Parent with variants</option><option value="variant">Variant product</option></select></div>}
 {step===1&&<div className="grid gap-3 md:grid-cols-2"><input className="erp-input" placeholder="Category ID" value={form.category_id} onChange={e=>set('category_id',e.target.value)}/><input className="erp-input" placeholder="Sub category ID" value={form.sub_category_id} onChange={e=>set('sub_category_id',e.target.value)}/><input className="erp-input" placeholder="Model" value={form.model} onChange={e=>set('model',e.target.value)}/><input className="erp-input" placeholder="Type" value={form.type} onChange={e=>set('type',e.target.value)}/></div>}
 {step===2&&<div className="grid gap-3 md:grid-cols-2"><input className="erp-input" placeholder="Supplier ID" value={form.supplier_id} onChange={e=>set('supplier_id',e.target.value)}/><input className="erp-input" placeholder="Supplier SKU" value={form.supplier_sku} onChange={e=>set('supplier_sku',e.target.value)}/><input className="erp-input" type="number" step="0.01" placeholder="Cost price" value={form.cost_price} onChange={e=>set('cost_price',e.target.value)}/></div>}
 {step===3&&<div className="grid gap-3 md:grid-cols-2"><input className="erp-input" type="number" placeholder={form.product_type==='parent'?'Parent stock disabled if variants exist':'Opening stock'} disabled={form.product_type==='parent'} value={form.opening_stock} onChange={e=>set('opening_stock',e.target.value)}/><input className="erp-input" type="number" placeholder="Low stock alert qty" value={form.low_stock_alert_qty} onChange={e=>set('low_stock_alert_qty',e.target.value)}/><p className="text-xs text-slate-500 md:col-span-2">Rule: Parent product stock is disabled when variants exist. Variant level stock should be added separately.</p></div>}
 {step===4&&<input className="erp-input" placeholder="Main image URL" value={form.image_url} onChange={e=>set('image_url',e.target.value)}/>} 
 {step===5&&<div>{form.product_type==='single'?<p className="text-sm text-slate-500">Single product selected. Variant section hidden.</p>:<><p className="mb-2 text-xs text-slate-500">Variants JSON. Popup/dropdown issue avoided by using clean editor here; full variant table can be extended.</p><textarea className="min-h-52 w-full rounded-lg border border-white/10 bg-[#070B14] p-3 font-mono text-xs outline-none focus:border-yellow-400/60" value={form.variants_json} onChange={e=>set('variants_json',e.target.value)}/></>}</div>}
 {step===6&&<textarea className="min-h-52 w-full rounded-lg border border-white/10 bg-[#070B14] p-3 font-mono text-xs outline-none focus:border-yellow-400/60" value={form.attributes_json} onChange={e=>set('attributes_json',e.target.value)}/>} 
 {step===7&&<pre className="max-h-[420px] overflow-auto rounded-xl border border-white/10 bg-[#070B14] p-4 text-xs">{JSON.stringify(form,null,2)}</pre>}
 </div><div className="flex justify-between"><button type="button" disabled={step===0} onClick={back} className="erp-btn-secondary"><ArrowLeft size={14}/> Back</button>{step<steps.length-1?<button type="button" onClick={next} className="erp-btn-primary">Next <ArrowRight size={14}/></button>:<button disabled={saving} className="erp-btn-primary"><Save size={14}/> Save Product</button>}</div></form>;
}
