// Full CMS sidebar menu. The Inventory Management app (src/inventory_app/)
// reuses the PRODUCT MANAGEMENT + INVENTORY sections of this list.
export const staticMenu = [
  {
    section: "PRODUCT MANAGEMENT",
    page_key: "products",
    pageKeys: ["products", "local_products"],
    page_name: "Local Products",
    path: "/product/local-products",
    icon: "BarChart3",
    exact: true,
  },
  {
    section: "PRODUCT MANAGEMENT",
    page_key: "images_dashboard",
    page_name: "Images Dashboard",
    path: "/product/images",
    icon: "Image",
    exact: true,
  },
  {
    section: "PRODUCT MANAGEMENT",
    page_key: "category_master",
    pageKeys: ["category_master", "categories"],
    page_name: "Category / Code Master",
    path: "/product/categories",
    icon: "Grid3X3",
    exact: true,
  },
  {
    section: "PRODUCT MANAGEMENT",
    page_key: "colour_master",
    pageKeys: ["colour_master", "colours"],
    page_name: "Colours",
    path: "/product/colours",
    icon: "Palette",
    exact: true,
  },
  {
    section: "PRODUCT MANAGEMENT",
    page_key: "sku_mapping",
    page_name: "SKU Mapping",
    path: "/product/sku-mapping",
    icon: "PackageSearch",
    exact: true,
  },
  {
    section: "INVENTORY",
    page_key: "inventory",
    page_name: "Inventory",
    path: "/inventory",
    icon: "Boxes",
    exact: false,
  },
  {
    section: "MARKETPLACE MANAGEMENT",
    page_key: "daraz_products",
    page_name: "Daraz Products",
    path: "/product/daraz-products",
    icon: "ShoppingBag",
    exact: true,
  },
  {
    section: "MARKETPLACE MANAGEMENT",
    page_key: "brighthub_products",
    page_name: "Website Products",
    path: "/product/brighthub-products",
    icon: "Store",
    exact: true,
  },
  {
    section: "REPORTS",
    page_key: "sales_dashboard",
    page_name: "Sales",
    path: "/reports/sales",
    icon: "BarChart3",
    exact: true,
  },
  {
    section: "REPORTS",
    page_key: "pricing",
    page_name: "Price Dashboard",
    path: "/price",
    icon: "DollarSign",
    exact: false,
  },
  {
    section: "ORDER MANAGEMENT",
    page_key: "orders",
    page_name: "Orders",
    path: "/order-management/orders",
    icon: "Package",
    exact: false,
  },
  {
    section: "ORDER MANAGEMENT",
    page_key: "order_customers",
    page_name: "Customers",
    path: "/order-management/customers",
    icon: "Users",
    exact: true,
  },
  {
    section: "ORDER MANAGEMENT",
    page_key: "product_trends",
    page_name: "Product Trends",
    path: "/order-management/product-trends",
    icon: "BarChart3",
    exact: true,
  },
  {
    section: "FINANCE",
    page_key: "daraz_finance_transactions",
    pageKeys: ["daraz_finance_transactions", "daraz_finance"],
    page_name: "Transactions",
    path: "/order-management/finance/transactions",
    icon: "DollarSign",
    exact: true,
  },
  {
    section: "FINANCE",
    page_key: "daraz_finance_income",
    pageKeys: ["daraz_finance_income", "daraz_finance"],
    page_name: "Income",
    path: "/order-management/finance/income",
    icon: "Wallet",
    exact: true,
  },
  {
    section: "MESSAGES",
    page_key: "message_templates",
    page_name: "Message Templates",
    path: "/order-management/message-templates",
    icon: "MessageSquare",
    exact: true,
  },
  {
    section: "CONFIGURATION",
    page_key: "marketplace_accounts",
    page_name: "Marketplace Accounts",
    path: "/marketplace/accounts",
    icon: "Store",
    exact: true,
  },
  {
    section: "CONFIGURATION",
    page_key: "daraz_metrics",
    page_name: "Daraz Metrics",
    path: "/marketplace/daraz-metrics",
    icon: "BarChart3",
    exact: true,
  },
  {
    section: "SUPPLIER MANAGEMENT",
    page_key: "suppliers",
    page_name: "Suppliers",
    path: "/suppliers",
    icon: "Truck",
    exact: true,
  },
  {
    section: "SETTINGS",
    page_key: "notifications",
    page_name: "Notifications",
    path: "/notifications",
    icon: "Bell",
    exact: true,
  },
  {
    section: "SETTINGS",
    page_key: "users",
    page_name: "Users",
    path: "/users",
    icon: "Users",
    exact: false,
  },
  {
    section: "SETTINGS",
    page_key: "access_control",
    page_name: "Access Control",
    path: "/access-control",
    icon: "ShieldCheck",
    exact: true,
  },
  {
    section: "SETTINGS",
    page_key: "logs",
    page_name: "Logs",
    path: "/logs",
    icon: "Monitor",
    exact: true,
  },
  {
    section: "SETTINGS",
    page_key: "order_sync_settings",
    page_name: "Daraz Sync Settings",
    path: "/order-management/sync-settings",
    icon: "Clock",
    exact: true,
  },
  {
    section: "SETTINGS",
    page_key: "server_storage",
    page_name: "Server Storage",
    path: "/settings/server-storage",
    icon: "HardDrive",
    exact: true,
  },
];
